### ISSUE TITLE
The `exec-path` subcommand is not listed in help

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/eask#15]
When I run `eask` with no arguments, the command `exec-path` is not listed, but it works nonetheless and seems to print correct exec-path.

![image](https://user-images.githubusercontent.com/2664959/170508798-91e0c8ee-769b-40a7-9e24-aaf6f779addd.png)

**Comment by jcs090218** [comment]
`exec-path` is alias of `path`

```
path                    print the PATH (exec-path) from workspace                                                                                                 [aliases: exec-path]
```

One great feature from `yargs`, see:

https://github.com/emacs-eask/eask/blob/1463c8354740788bdcba5c90a8a4eec4665e393e/cmds/core/exec-path.js#L22

**Comment by Fuco1** [comment]
Ah yea, honestly didn't notice the output on the right margin.  Thanks! :)
