### ISSUE TITLE
Do not print ansi sequences in DUMB terminal

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/eask#33]
When running ert-runner inside emacs with overseer.el, eask prints a lot of ansi sequences which are not interpreted.

In a DUMB terminal we should avoid printing ansi escapes.

![image](https://user-images.githubusercontent.com/2664959/171679385-9052eb04-fd48-4e14-b257-5c28a46b8fbb.png)

**Comment by jcs090218** [comment]
Resolved in #34! Thanks for reporting this issue! :D
