### ISSUE TITLE
Support nix install

### ISSUE THREAD

**Issue by ericdallo** [emacs-eask/eask#47]
It'd be nice to have eask available on nixpkgs like [cask](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/cask/default.nix)

**Comment by jcs090218** [comment]
Thanks for the suggestion!

I never contribute to nixpkg before, but I will look into it! :)

**Comment by jcs090218** [comment]
I have tried to give it a shot in https://github.com/NixOS/nixpkgs/pull/178053 but not sure how it would work? WDYT? 😅 Would be great if someone could point me with some directions?

**Comment by ericdallo** [comment]
LGTM @jcs090218! Maybe @thiagokokada could help reviewing/merging that PR?

**Comment by jcs090218** [comment]
It get merged in https://github.com/NixOS/nixpkgs/pull/189789. Thanks to everyone who participate in this! 🎉❤️

**Comment by ericdallo** [comment]
awesome, congrats and thanks @jcs090218
