### ISSUE TITLE
Add support for specifying load path for buttercup

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/eask#8]
Often people place a "helper" file with helper defuns for tests.  For example https://github.com/Fuco1/org-radiobutton/tree/master/tests

When I run the tests, I pass `-L tests` to buttercup:

```
cask exec buttercup  -L . -L tests
```

This will make sure the test files can `require` the helper.

Maybe we could include the tests directory in the load path automatically, or add a flag to pass the load path explicitly.

**Comment by jcs090218** [comment]
Maybe `(load-path "tests/")` would work? See https://emacs-eask.github.io/DSL/#-load-paths-rest-paths

Extra information, `Eask`-file is a Elisp file hence you could just do:

```elisp
(add-to-list 'load-path "./test/")
```

Hope the above information help! :)

**Comment by Fuco1** [comment]
Man this is so boss.  Adding the `load-paths` works.  Also I didn't realize the file is interpreted, since cask isn't and only the DSL works there.

Seriously loving your work, it's going to get huge believe me.  I'm going to switch all my packages to eask including dash which I co-maintain, that will give you a ton of exposure hopefully.  It's super early stages but already it feels very right.  Great job.

![image](https://user-images.githubusercontent.com/2664959/170510193-ea793d0a-1c5e-4143-a43e-8ff4865c9372.png)

**Comment by jcs090218** [comment]
That would be awesome! ❤️ 😁 

Let me know if you need help! Here is a list of [Real project examples](https://emacs-eask.github.io/Examples/Real-project-examples/). And some PR links I have helped integrating Eask to their projects:

* https://github.com/emacs-lsp/dap-mode/pull/596
* https://github.com/godotengine/emacs-gdscript-mode/pull/113
* https://github.com/rust-lang/rust-mode/pull/444
