### ISSUE TITLE
Add an option to skip "dependency check"

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/eask#9]
I'm absolutely blown away that just doing `eask elsa` will fetch the package, install everything and run Elsa on the package file.  This is exactly the UX I was hoping for with Cask, but it is a bit more complicated there.  This works amazing.

I would even go as far as make `flycheck-elsa` use eask as "execution backend", but one thing is a bit inefficient.  When I run `eask elsa` this step

```
Loading package information... done ✓
  - Skipping elsa (20220223.2021)... already installed ✗
```

takes a bit of time, maybe a second or so.  This is completely fine in CI, but might be a problem if we are starting this from flycheck after every file change.  If we could do a `--skip-dependency-check` or something similar and just assume it is installed, it would be an amazing way to plug linters (not just Elsa but anything) to flycheck.

**Comment by Fuco1** [comment]
What should I do to update to the version with patch #13 applied?  

I don't fully understand the relationship of the javascript code and elisp here.

**Comment by Fuco1** [comment]
Ah yea, I'm still on E26.3 :D I'll test it after I upgrade but I think your pull request fixed it so we can close this issue to avoid clutter?

**Comment by jcs090218** [comment]
> What should I do to update to the version with patch https://github.com/emacs-eask/eask/pull/13 applied?

I will recommend you install it from source, see https://emacs-eask.github.io/Getting-Started/Install-Eask/#-source. That way you will be able to use whatever it's on the master branch.

And if you want to test a branch, you can simply switch to the test branch you want. For example:

```
git clone https://github.com/{owner}/eask.git --branch {name}
```

it this case will be

```
git clone https://github.com/emacs-eask/eask.git --branch simplify
```

And just make sure your environment path is correct to [bin](https://github.com/emacs-eask/eask/tree/master/bin) folder. You can run `eask locate` to find out which eask is currently running; it's useful when you have multiple eask installed at a time.

> I don't fully understand the relationship of the javascript code and elisp here.

Hope these links would help you understand more about Eask: 😄 

* https://emacs-eask.github.io/Contributing/Developing-Eask/
* https://emacs-eask.github.io/Implementation/CLI-Yargs/

(mainly the [yargs](https://github.com/yargs/yargs))

> Ah yea, I'm still on E26.3 :D I'll test it after I upgrade but I think your pull request fixed it so we can close this issue to avoid clutter?

Yes, feel free to reopen this issue if the issue persist! :)
